name: efishent
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast
  - bowtie
  - entrez-direct
  - glpk=5.0
  - jellyfish
  - libgomp      # [linux]
  - llvm-openmp  # [osx]
  - pip
  - pysam
  - python=3.9
  - rnastructure
