name: efishent
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast
  - bowtie==1.3.1
  - entrez-direct
  - jellyfish
  - libgomp      # [linux]
  - llvm-openmp  # [osx]
  - pip
  - python>=3.8,<3.11