{% set version = "0.0.3" %}

package:
    name: efishent
    version: {{ version }}
source:
    path: ..

build:
    build: 1
    preserve_egg_dir: True
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
      - efishent = eFISHent.cli:main
      - eFISHent = eFISHent.cli:main

requirements:
  host:
    - pip
    - python>=3.8
    - llvm-openmp  # [osx]
  run:
    - biopython
    - blast
    - bowtie==1.3.1
    - entrez-direct
    - gtfparse
    - jellyfish
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - luigi
    - matplotlib-base
    - numpy>=1.21
    - pandas>1.0
    - pyarrow>=8.0.0
    - pyomo
    - python>=3.8

test:
  commands:
    - pip check
    - efishent --help
    - eFISHent --help

about:
  home: https://github.com/bbquercus/eFISHent/
  summary: A tool to design RNA FISH oligos/probes
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - BBQuercus   