{% set name = "eFISHent" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eFISHent-{{ version }}.tar.gz
  sha256: 6c10f608b078a8085dabaf2f8e58c62499fe6afd1aa7536fbdb2050cb34ff601

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - efishent = eFISHent.cli:main
    - eFISHent = eFISHent.cli:main

requirements:
  host:
    - pip
    - python >=3.7
    - llvm-openmp  # [osx]
  run:
    - biopython
    - blast
    - bowtie
    - entrez-direct
    - gtfparse
    - jellyfish
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - luigi
    - matplotlib-base
    - numpy
    - pandas
    - pyarrow
    - pyomo
    - python >=3.7

test:
  commands:
    - pip check
    - efishent --help
    - eFISHent --help

about:
  home: https://github.com/bbquercus/eFISHent/
  summary: A tool to design RNA FISH oligos/probes
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - BBQuercus   