package:
    name: "efishent"
    version: 0.0.3
source:
    path: ..

build:
    build: 1
    preserve_egg_dir: True
    script: python -m pip install --ignore-installed .
    entry_points:
      - efishent = eFISHent.cli:main
      - eFISHent = eFISHent.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - llvm-openmp  # [osx]
  run:
    - blast
    - bowtie
    - entrez-direct
    - jellyfish
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - python >=3.8

test:
  commands:
    - pip check
    - efishent --help
    - eFISHent --help

about:
  home: https://github.com/bbquercus/eFISHent/
  summary: A tool to design RNA FISH oligos/probes
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - BBQuercus   