name: Build and Publish Conda Package
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          conda-version: '4.10.x'

      - name: Build Conda package
        run: conda build -c conda-forge -c bioconda .

      - name: Publish Conda package to Anaconda
        uses: conda-incubator/anaconda-client-publish@v1
        with:
          anaconda-token: ${{ secrets.ANACONDA_TOKEN }}
          packages: |
            ./path/to/linux/*.tar.bz2
            ./path/to/macos/*.tar.bz2
