name: main

on:
  - push
  # release:
  #   types: [published]

jobs:
  # Direct upload to conda
  conda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: actions/conda
      with:
        subdir: "conda"
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        channels: 'conda-forge bioconda'
        platforms: "osx linux"