name: Build and Publish Pypi Package
on:
  push:
    branches:
      - main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://upload.pypi.org/legacy/
        user: bbquercus
        password: ${{ secrets.PYPI_API_TOKEN }}