name: Tests

on:
  - push
  - pull_request

jobs:
  # Unittests
  test:
    name: Test (${{ matrix.python-version }}, MacOS)
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: ["3.7.4"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Verify conda
        run: |
          conda activate test
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install codecov
          python -m pip install tox
          python -m pip install tox-conda
          python -m pip install tox-gh-actions
      - name: Run tox
        run: tox -e py
      - name: Upload coverage reports to Codecov
        run: codecov
        env:
          super_secret: ${{ secrets.CODECOV }}

  # Important checks but not reliant on different versions
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: run tox style
        run: tox -e style
