name: Tests

on:
  - push
  - pull_request

jobs:
  # Unittests
  test:
    name: Test (${{ matrix.python-version }}, ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "macos-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install codecov
          python3 -m pip install tox
          python3 -m pip install tox-conda
          python3 -m pip install tox-gh-actions
      - name: Run tox
        run: python3 -m tox -e py
      - name: Upload coverage reports to Codecov
        run: codecov
        env:
          super_secret: ${{ secrets.CODECOV }}

  # Important checks but not reliant on different versions
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tox
        run: tox -e style
