name: Tests

on:
  - push
  - pull_request

jobs:
  test-ubuntu:
    name: Test (${{ matrix.python-version }}, MacOS)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda install deps
      - name: Install tox
        run: python -m pip install --upgrade pip
          pip install tox tox-gh-actions tox-conda
      - name: Run tox
        run: tox
