name: Tests

on:
  - push
  - pull_request

jobs:
  test-ubuntu:
    name: Test (${{ matrix.python-version }}, MacOS)
    runs-on: "macos-latest"
    strategy:
      matrix:
        python-version: ["3.7.4"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
      - name: Verify conda
        run: |
          conda activate test
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install tox-gh-actions
          python -m pip install tox-conda
      - name: Run tox
        run: tox
