name: Tests

on:
  - push
  - pull_request

jobs:
  test-ubuntu:
    name: Test (${{ matrix.python-version }}, Ubuntu)
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: activate conda
        run: conda activate test
      - name: install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
          python -m pip install tox-gh-actions
          python -m pip install tox-conda
      - name: run tox
        run: tox
